Repository 100-hours-a-week/2-hertz-fe, pull requests merged in 2025-06, with the labels that each got.

#72 v1 코드리뷰 피드백 기반 리팩토링
  package.json
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/app/chat/individual/page.tsx
  src/app/login/page.tsx
  src/components/onboarding/interests/UserPreferenceForm.tsx
Labels: endhancement, refactor

#78 튜닝 리포트 페이지 API 연결 및 Optimistic UI 적용
  package.json
  pnpm-lock.yaml
  public/images/report.png
  src/app/report/page.tsx
  src/components/report/ReactionGroup.tsx
  src/components/report/ReportLoading.tsx
  src/hooks/useTuningReportsQuery.ts
  src/lib/api/report.ts
Labels: feature, api

#80 매칭 SSE 수락/거절 API 연동 및 채팅방 UI 동적 반영
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/app/chat/individual/page.tsx
  src/app/profile/[partnerId]/page.tsx
  src/components/chat/common/ReceiverMessage.tsx
  src/components/chat/common/SenderMessage.tsx
  src/components/layout/ChatHeader.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/lib/api/matching.ts
Labels: endhancement, design, api

#82 feat: 도커 CI/CD 적용
  .dockerignore
  .github/workflows/docker-cicd-frontend.yml
  Dockerfile
Labels: feature

#83 fix: 백틱 제거, workflow ignore 추가
  .github/workflows/cicd-frontend.yml
  .github/workflows/docker-cicd-frontend.yml
Labels: bug

#84 SSE 핸들러 안정화 및 매칭 모달 상태관리 버그 수정
  src/components/common/WaitingModal.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/hooks/useSSE.ts
  src/stores/modal/useConfirmModalStore.ts
Labels: bug

#88 공통 / 일반 관심사 분리 및 매칭되지 않은 사용자 키워드 블러 처리
  src/app/mypage/page.tsx
  src/app/profile/[partnerId]/page.tsx
  src/app/report/page.tsx
  src/components/common/KeywordTag.tsx
  src/components/matching/individual/KeywordTagGroup.tsx
  src/lib/api/matching.ts
  src/lib/api/user.ts
Labels: bug, feature

#93 v1 QA 기반 수정사항 반영 및 매칭/채팅/알림 개선
  src/app/alarm/page.tsx
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/app/globals.css
  src/app/profile/[partnerId]/page.tsx
  src/app/report/page.tsx
  src/components/chat/UnavailableChannelBanner.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/WaitingModal.tsx
  src/components/layout/ChatHeader.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/components/matching/individual/KeywordTagGroup.tsx
  src/stores/modal/useWaitingModalStore.ts
Labels: bug, endhancement, api

#95 채팅방 나가기 API 연결
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/components/common/ConfirmModal.tsx
  src/components/layout/BottomNavigationBar.tsx
  src/lib/api/chat.ts
Labels: bug, api

#97 바텀 네비게이션 및 헤더에 새 메세지 · 알림 SSE 연결
  public/images/notification-new.png
  public/images/notification-normal.png
  src/components/layout/BottomNavigationBar.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/components/layout/Header.tsx
  src/hooks/useSSE.ts
  src/stores/chat/useNavNewMessageStore.ts
  src/stores/chat/useNewAlarmStore.ts
Labels: design, api

#99 새 메세지 수신 SSE 연결 및 팝업 알림 UI 구현
  src/components/common/NewMessageToast.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/components/matching/individual/KeywordTagGroup.tsx
  src/hooks/useSSE.ts
  src/stores/modal/useNewMessageStore.ts
Labels: feature, api

#101 SSE 기반 채팅 목록 실시간 갱신 기능 추가 및 폴링 방식 제거
  src/app/chat/individual/page.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/lib/queryClient.ts
Labels: endhancement, api

#104 SSE 버그 수정 및 QA 피드백 기반 예외 처리 개선
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/components/common/NewMessageToast.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/components/onboarding/information/UserInformationForm.tsx
  src/hooks/useSSE.ts
  src/lib/schema/onboardingValidation.ts
  src/stores/modal/useMatchingResponseStore.ts
Labels: bug, endhancement

#106 나간 채팅방 및 비로그인 유저 접근 예외 처리 및 `AuthGuard` 적용
  src/app/alarm/page.tsx
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/app/layout.tsx
  src/components/layout/AuthGuard.tsx
  src/lib/api/chat.ts
Labels: bug

#107 온보딩 단계 분기 처리 및 인증 / 채팅 예외 처리 개선
  src/components/layout/AuthGuard.tsx
  src/components/onboarding/information/UserInformationForm.tsx
  src/components/onboarding/interests/UserPreferenceForm.tsx
  src/lib/api/chat.ts
Labels: bug, endhancement

#108 v2.0.1
  src/app/alarm/page.tsx
  src/app/chat/individual/[channelRoomId]/page.tsx
  src/app/layout.tsx
  src/components/layout/AuthGuard.tsx
  src/components/onboarding/information/UserInformationForm.tsx
  src/components/onboarding/interests/UserPreferenceForm.tsx
  src/lib/api/chat.ts
Labels: release

#114 Refresh Token 만료 시 무한 요청 방지를 위한 예외 처리 추가
  src/lib/api/auth.ts
Labels: endhancement

#115 `REFRESH_TOKEN_INVALID` 응답 시 무한 리다이렉트 이슈 해결 - 만료된 RT로 인한 자동 로그인 루프 방지
  src/lib/api/auth.ts
Labels: bug

#116 v2.0.2
  src/app/chat/individual/page.tsx
  src/components/common/ConfirmModal.tsx
  src/components/layout/ClientLayoutContent.tsx
  src/lib/api/auth.ts
Labels: release
